### ISSUE TITLE
Pick a more appropriate name for `with_error_fn`? 

### ISSUE THREAD

**Issue by wfxr** [Xuanwo/backon#11]
@Xuanwo This crate is awesome! I never thought of a retry mechanism that could be implemented in such an elegant way. :+1:

However the function name `with_error_fn` is somewhat ambiguous for me. I cannot guess what it is used for without reading the comments.

How about renaming it to `continue_if` or `break_if` (on the contrary), following the naming convention in [`std::ops::ControlFlow`](https://github.com/rust-lang/rust/blob/08871139915b95ec868aff807f224f78d00f4311/library/core/src/iter/traits/iterator.rs#L2166-L2172):

```rust
let content = fetch
    .retry(ExponentialBackoff::default())
    .continue_if(|e| e.to_string() != "EOF") // continue if error is not "EOF"
    .await?;
```

v.s.

```rust
let content = fetch
    .retry(ExponentialBackoff::default())
    .break_if(|e| e.to_string() == "EOF") // stop retrying when error is "EOF"
    .await?;
```

Personally I think `break_if` is a good choice. What do you think of it?

**Comment by Xuanwo** [comment]
Sorry for the late response. This idea is quick and cool.

How about `when`?

```rust
let content = fetch
    .retry(ExponentialBackoff::default())
    .when(|e| e.to_string() == "EOF") // If error is retryable, retry it.
    .await?;
```

**Comment by Xuanwo** [comment]
> Can I help with this change?

Of course! Welcome, go for this!

Although `backon` is a `0.0.x` version, keeping API compatible is still an excellent choice for our users. Please consider adding a `#[deprecate]` message for `with_error_fn` instead of removing it directly.

**Comment by wfxr** [comment]
> Although backon is a 0.0.x version, keeping API compatible is still an excellent choice for our users. Please consider adding a #[deprecate] message for with_error_fn instead of removing it directly.

Good advice, thanks!
