### ISSUE TITLE
Panicking after upgrade

### ISSUE THREAD

**Issue by djc** [Xuanwo/backon#128]
After upgrading to version 1, we got the following panic message:

```
Error: `panic: panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/backon-1.0.0/src/sleep.rs:33:9:
no sleeper has been configured, consider enabling features or provide a custom implementation` (on utils/src/tracers.rs:44)
```

IMO making it "silently" panicking (that is, there's no explicit API for picking the sleeper) is a pretty bad problem if you want to build a production-worthy library, and none of the examples make it clear that a sleeper impl must be configured.

**Comment by Xuanwo** [comment]
Thank you for the report. I have added an upgrade guide for version 0.5: https://github.com/Xuanwo/backon/releases/tag/v0.5.0. However, it doesn't seem sufficient.

Do you think it would be better to include `tokio-sleep` in the `default` feature?

**Comment by djc** [comment]
Adding the default features is a much better solution, thanks.

Typically I suggest that Cargo features should be necessary but not sufficient to change (significant) behavior (that is not caught by compilation failures). Even more so because Cargo features can be implicitly changed by other crates pulled into your dependency graph. So I would suggest that your API take an explicit argument for the sleeper impl used. For example, `ExponentialBuilder::default()` could become `ExponentialBuilder::tokio()` instead, or you could expose wrapper types (I prefer to avoid type aliases) as like `backon::tokio::ExponentialBuilder`.
