### ISSUE TITLE
Why not using futures-timer ?

### ISSUE THREAD

**Issue by NumberFour8** [Xuanwo/backon#153]
The futures-timer (https://crates.io/crates/futures-timer) crate is runtime agnostic and also supports `gloo-timers` for WASM environments.

Why not using that one instead of `gloo-timers` directly? This also covers the cases, when e.g. someone is not using `tokio`, but `async-std`.

**Comment by Xuanwo** [comment]
Hi, thank you first for raising this.

All timer (a.k.a sleeper in this project) implementation are optional. Feel free to contribute futures-timer support if you are interested.

**Comment by NumberFour8** [comment]
Ok, thanks for your response!
I will prepare a PR which adds the `futures-timer` support then :)

**Comment by NumberFour8** [comment]
Comments on what to improve are welcome: https://github.com/Xuanwo/backon/pull/154/
