### ISSUE TITLE
the exponential strategy is likely to panic when it exceeds the upper bound of u64

### ISSUE THREAD

**Issue by Xuanwo** [Xuanwo/backon#38]
from [reddit](https://www.reddit.com/r/rust/comments/10wodyu/comment/j7oqgkz/?utm_source=share&utm_medium=web2x&context=3):

> the exponential strategy is likely to panic when it exceeds the upper bound of u64. see Duration::mul_f32()
>
> a safer alternative to it is Dutation::saturating_mul()

**Comment by balroggg** [comment]
We use `f32` as a factor in exponential strategy
https://github.com/Xuanwo/backon/blob/a706c0fc52f8743415aff7b02350984135018e14/src/exponential.rs#L40
But rust has [saturating_mul](https://doc.rust-lang.org/std/time/struct.Duration.html#method.saturating_mul) that take `u32`.
Should we change this factor or somehow validate the builder for that case?
