### ISSUE TITLE
Can backoff reset?

### ISSUE THREAD

**Issue by xlovelace** [Xuanwo/backon#52]
I use ExponentialBackoff to retry in 1s..2s..4s then connected.
Then disconnected again and start retry in 8s...16s...32s.
What i want is backoff.reset(),then retry in 1s..2s..4s in second retry.

**Comment by furkankly** [comment]
> No need to reset. Please retain the `ExponentialBuilder` and create a new `ExponentialBackoff` via `build`.

And then how do we supply the new backoff? `.retry()` seems to only accept a builder, not a backoff. Let's say I want to create a new retry sequence in the middle of another one based on a specific error using `when`, how do I use the retained builder, create a new backoff and supply it.

Can you please provide an example on this?
