### ISSUE TITLE
Does not work out of the box with wasm32-unknown-unknown (but there's a workaround)

### ISSUE THREAD

**Issue by wackazong** [Xuanwo/backon#59]
When using the crate in a project targeting wasm32-unknown-unknown, the following needs to be added to the project's `cargo.toml`:

`instant = { version = "0.1.12", features = ["wasm-bindgen"] }`

Otherwise an error [described here](https://github.com/rustwasm/wasm-bindgen/issues/2215) is logged (in my case to the browser console).

**Comment by Xuanwo** [comment]
backon doesn't call `now()` and `fastrand` already uses `instant` in `wasm32`. Can you provide more detailed repro for this issue?

**Comment by wackazong** [comment]
Interesting. I will try to find out why this is happening.

**Comment by Xuanwo** [comment]
Please feel free to reopen it if you can backon doesn't work on wasm.

**Comment by wackazong** [comment]
Ok, I could narrow it down to the use of tokio::time::sleep. It can be replaced with gloo_timers in wasm32 as far as I can see. I could submit a pull request if you so wish. I would use cfg macros to replace tokio::time::sleep with gloo_timers' sleep functionality if the crate is compiled with `target_arch = "wasm32"`.

**Comment by Xuanwo** [comment]
> Ok, I could narrow it down to the use of tokio::time::sleep. It can be replaced with gloo_timers in wasm32 as far as I can see. I could submit a pull request if you so wish. I would use cfg macros to replace tokio::time::sleep with gloo_timers' sleep functionality if the crate is compiled with `target_arch = "wasm32"`.

Thanks, I also want to remove the hard dependencies of tokio Sleep. Maybe this change can be implemented based on that.
